---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: network
    app.kubernetes.io/name: pcidevices-manager
    app.kubernetes.io/version: 0.0.1-dev
  name: pcidevices-manager
  namespace: harvester-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: network
      app.kubernetes.io/name: pcidevices-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: network
        app.kubernetes.io/name: pcidevices-manager
        app.kubernetes.io/version: 0.0.1-dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/os
                    operator: In
                    values:
                      - linux
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app.kubernetes.io/name
                      operator: In
                      values:
                        - pcidevices-manager
                    - key: app.kubernetes.io/component
                      operator: In
                      values:
                        - network
                topologyKey: kubernetes.io/hostname
              weight: 1
      containers:
        - image: harvester/pcidevices:master-head
          imagePullPolicy: IfNotPresent
          name: network
          command:
            - pcidevices
          args:
            - manager
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 250m
              memory: 256Mi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccountName: pcidevices