apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: pcidevices
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 0.0.2-dev
  name: pcidevices
  namespace: harvester-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pcidevices
rules:
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "devices.harvesterhci.io" ]
    resources: [ "pcidevices", "pcidevices/status", "pcideviceclaims" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: pcidevices
    app.kubernetes.io/component: operator
    app.kubernetes.io/version: 0.0.2-dev
  name: pcidevices
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pcidevices
subjects:
  - kind: ServiceAccount
    name: pcidevices
    namespace: harvester-system